### ISSUE TITLE
Issue when loading fall-back precision map

### ISSUE THREAD

**Issue by skarlosdeus** [ameyagodbole/Prob-CBR#4]
Hello there,

i would like to ask if you have solved the issue that you have also mentioned as a comment: 

  File "prob_cbr/pr_cbr.py", line 981, in <module>
    main(args)
  File "prob_cbr/pr_cbr.py", line 928, in main
    prob_cbr_agent.do_symbolic_case_based_reasoning()
  File "prob_cbr/pr_cbr.py", line 372, in do_symbolic_case_based_reasoning
    for ex_ctr, ((e1, r), e2_list) in enumerate(tqdm(self.train_map.items())):
  File "/home/scarlos/anaconda3/envs/seal/lib/python3.6/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
RuntimeError: dictionary changed size during iteration

Thanks.

**Comment by ameyagodbole** [comment]
Can you confirm that you are on the latest commit? I can't find the line that is throwing an error for you in the main branch

**Comment by skarlosdeus** [comment]
@ameyagodbole  Yes, your comment is placed in line 472:

### not sure why I am getting RuntimeError: dictionary changed size during iteration.

I have tackled this by copying my dict structure to another one, but can you propose anything else?

Kind regards.

**Comment by ameyagodbole** [comment]
Oh, I see. Well, https://github.com/ameyagodbole/Prob-CBR/blob/8bc8678c33baeb22a0ba56c59cfe5becc0a0cc81/prob_cbr/pr_cbr.py#L473 is the solution. There is no error after this. 

The comment is a bit misleading but we know why the error occurs. It is because the `defaultdict` gets updated if you ask for a new key.
